dist: xenial
os: linux
language: node_js
node_js:
- node
services:
- docker
addons:
  sauce_connect: true
before_install:
- docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-tag-1.37.36-64bit
  bash
before_script:
- python -m SimpleHTTPServer &
script:
- docker exec -it emscripten make deps all
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
  - viz.js
  - viz.es.js
  - full.render.js
  - lite.render.js
  skip_cleanup: true
  on:
    tags: true
